apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: sentiment-bot-external-secret
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: sentiment-bot-kv # {vault namespace}-{key vault}
        kind: ClusterSecretStore
    target:
        name: sentiment-bot-secrets # A Kubernetes Secret to create
    dataFrom:
        - extract:
              key: # A Vault Secret name (contains keys and values) || Either dev or prod
