# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Or a more recent version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.3.0 # Match the version in requirements-dev.txt
    hooks:
    -   id: black
        language_version: python3.11 # Ensure it uses the correct Python version

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0 # Match the version in requirements-dev.txt
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0 # Match the version in requirements-dev.txt
    hooks:
    -   id: flake8
        # args: ["--max-line-length=88", "--extend-ignore=E203"] # Can be set here or in .flake8

-   repo: local
    hooks:
    -   id: pytest
        name: pytest (unit tests & coverage)
        entry: bash -c '. .venv/bin/activate && pytest --cov=src --cov-fail-under=80'
        language: system
        args: ["--cov=src", "--cov-fail-under=80"]
        pass_filenames: false
        stages: [commit]

# mypy hook can be added if desired, but sometimes it's slower and run separately
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v1.3.0'  # Match your mypy version
#     hooks:
#     -   id: mypy
#         args: [--config-file=pyproject.toml]
#         # exclude: ^tests/ # if you don't want to type-check tests initially
