[tool.black]
line-length = 88
target-version = ['py39'] # Matches our project's Python version

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
# disallow_untyped_defs = true # Consider enabling for stricter checks
# ignore_missing_imports = true # Useful if some dependencies lack type stubs
